name = ("Manny")

#print (len(name))
#print (name.find("y"))
#print (name.capitalize())
#print (name.upper())
#print (name.lower())
#print (name.isdigit())
#print (name.isalpha())
#print(name.count("n"))
#print(name.replace("a" , "o"))
#print(name*3)