name = input("Hi, what's your name: ")
age = int(input("How old are you?: "))
height = float(input("How tall are you?: "))
#age = age + 1 (only for int)
print("Hello "+name)
print("You are "+str(age)+" years old")
print("You're "+str(height)+ "ft tall")